### PR TITLE
Add assigning the ROOT variable for fusiondirectory customization

### LINKED ISSUE #3: three-level domain fails
https://github.com/tiredofit/docker-openldap-fusiondirectory/blob/ce1c025cde38f3248838f2d6d45b523deebd54e7/install/assets/custom-scripts/001-install-fusiondirectory.sh#L21-L42

I have a subdomain that I am trying to implement this at - `trans.hobbithole.blue`, and when these lines are reached, line 28 correctly assigns it, but then it gets reassigned at line 40 incorrectly. It ends up being "dc=trans,dc=blue". This is then the suffix that is used to build the directory structure.

It almost seems like these two loops are doing the same thing with setting the `BASE_DN` variable. 

Actually, the more I read through this, the more confused I get. `SUFFIX` isn't used anywhere else, so it has to just be a way to compute what the `BASE_DN` is. `ROOT` is used elsewhere, but that should be easy enough to get from the `BASE_DN`.

If I were to write this, I would have chosen the implementation at lines 21-28, as it's clearer, cleaner, and works for multiple subdomains. I don't see why `BASE_DN` needs to be reset below.

### PR DESCRIPTION
**Pull request by smacz42**
Helps to fix #3

### CODE REVIEW

**Comment by smacz42** [comment]
@tiredofit Please let me know if any additional work needs to be done once this inherits the merge from https://github.com/tiredofit/docker-openldap/pull/3 upstream. (rebase, etc.)

**Comment by tiredofit** [comment]
It should have triggered an auto build of openldap-fusiondirectory post build of OpenLDAP. Dockerhub says theres a new :latest" since about 2 hours ago. I haven't created an actual tag for it yet, but will be doing so shortly. Hopefully this resolves the issue for you?

**Comment by tiredofit** [comment]
I've merged this commit - should be under :latest now. Any success?

**Comment by smacz42** [comment]
Will check soon. Thanks for the quick work.

Regards,

On April 9, 2019 10:19:51 AM EDT, Dave Conroy <notifications@github.com> wrote:
>I've merged this commit - should be under :latest now. Any success?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tiredofit/docker-openldap-fusiondirectory/pull/4#issuecomment-481272090

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
