### PR TITLE
make .sh files in custom-scripts executable

### PR DESCRIPTION
**Pull request by joergmschulz**
see #29

### CODE REVIEW

**Comment by tiredofit** [comment]
Hi sorry - can you check the new branches that were created yesterday? I haven't finished off what I started yesterday, I did catch this exact same executible bit set on the branches.

I hope to finish by the end of this week to support the various backend of OpenLDAP and various branch of FusionDirectory.

**Comment by tiredofit** [comment]
Actually, I feel this won't work as well as we haven't injected all the files quite yet.
 
I believe this change will need to be performed on a parent level.

**Comment by joergmschulz** [comment]
indeed. Now the scripts run perfectly.

**Comment by tiredofit** [comment]
Sweet! Enjoy FusionDirectory - Sounds like you've got quite the stack in place. All thats left is to use https://github.com/tiredofit/docker-lemonldap :)

**Pull request closed without merging**
